---
defaults:
  -
    scope:
      path: ""
      type: post
    values:
      layout: post
  -
    scope:
      path: for-sale
      type: post
    values:
      layout: for-sale-item
permalink: "/:categories/:title"
